// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-sourcing-requests.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-sourcing-requests.ts
var list_sourcing_requests_default = defineTool({
  name: "list_sourcing_requests",
  title: "List sourcing requests",
  description: "List the signed-in user's sourcing requests, newest first. Optionally filter by status.",
  inputSchema: {
    status: z.string().optional().describe("Filter by status, e.g. pending, quoted, accepted, completed."),
    limit: z.number().int().optional().describe("Maximum rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("sourcing_requests").select("id,title,description,quantity,budget_per_unit,currency,status,delivery_country,eco_friendly,created_at").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { requests: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-sourcing-request.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_sourcing_request_default = defineTool2({
  name: "get_sourcing_request",
  title: "Get sourcing request",
  description: "Get one sourcing request with its quotes and recent messages.",
  inputSchema: { request_id: z2.string().describe("The sourcing request id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ request_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: request, error } = await supabase.from("sourcing_requests").select("*").eq("id", request_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!request) return { content: [{ type: "text", text: "Request not found or not accessible" }], isError: true };
    const [{ data: quotes }, { data: messages }] = await Promise.all([
      supabase.from("quotes").select("id,factory_name,total_cost,currency,moq,delivery_time_days,status,created_at").eq("sourcing_request_id", request_id).order("created_at", { ascending: false }),
      supabase.from("messages").select("id,content,sender_id,message_type,created_at").eq("sourcing_request_id", request_id).order("created_at", { ascending: false }).limit(20)
    ]);
    const payload = { request, quotes: quotes ?? [], recent_messages: messages ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/create-sourcing-request.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_sourcing_request_default = defineTool3({
  name: "create_sourcing_request",
  title: "Create sourcing request",
  description: "Submit a new sourcing request for the signed-in user.",
  inputSchema: {
    title: z3.string().describe("Short product title."),
    description: z3.string().describe("Detailed product specification and requirements."),
    quantity: z3.number().int().describe("Units required."),
    budget_per_unit: z3.number().optional().describe("Target price per unit."),
    currency: z3.string().optional().describe("Currency code, e.g. EUR or USD. Defaults to EUR."),
    delivery_country: z3.string().optional().describe("Destination country."),
    delivery_address: z3.string().optional().describe("Destination address."),
    eco_friendly: z3.string().optional().describe("Eco-friendly preference, e.g. yes / no / preferred."),
    notes: z3.string().optional().describe("Any extra notes for the sourcing agent.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("sourcing_requests").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      description: input.description,
      quantity: input.quantity,
      budget_per_unit: input.budget_per_unit ?? 0,
      currency: input.currency ?? "EUR",
      delivery_country: input.delivery_country ?? "",
      delivery_address: input.delivery_address ?? "",
      eco_friendly: input.eco_friendly ?? null,
      notes: input.notes ?? null
    }).select("id,title,status,created_at").maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { request: data } };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_orders_default = defineTool4({
  name: "list_orders",
  title: "List orders",
  description: "List the signed-in user's orders with status, totals and tracking info.",
  inputSchema: {
    status: z4.string().optional().describe("Filter by order status."),
    limit: z4.number().int().optional().describe("Maximum rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("orders").select("id,order_number,product_name,quantity,total_amount,status,eta,buckydrop_tracking_number,created_at").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { orders: data ?? [] } };
  }
});

// src/lib/mcp/tools/send-request-message.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var send_request_message_default = defineTool5({
  name: "send_request_message",
  title: "Send message on a sourcing request",
  description: "Post a chat message to the sourcing agent on one of the signed-in user's sourcing requests.",
  inputSchema: {
    request_id: z5.string().describe("The sourcing request id (uuid)."),
    content: z5.string().describe("Message body to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ request_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const body = content.trim();
    if (!body) return { content: [{ type: "text", text: "Message content is empty" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("messages").insert({ sourcing_request_id: request_id, sender_id: ctx.getUserId(), content: body }).select("id,created_at").maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { message: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "chmoabjmtbbqdrgigspm";
var mcp_default = defineMcp({
  name: "final-version-website",
  title: "Final version website",
  version: "0.1.0",
  instructions: "Tools for the Equilinq sourcing platform. Use them to list and inspect the signed-in user's sourcing requests and quotes, create new sourcing requests, track orders, and message the sourcing agent.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_sourcing_requests_default, get_sourcing_request_default, create_sourcing_request_default, list_orders_default, send_request_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
